### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by tlf30** [34-Matt/Latex-Math#1]
What is this repo licensed under? No license has been placed in the repo.

**Comment by 34-Matt** [comment]
Currently, this is just a project for a class to begin training at DNN to identify handwritten characters.  What would be a good license such that others can use and modify the code?

**Comment by tlf30** [comment]
MIT license is a good one for this type of project.

**Comment by 34-Matt** [comment]
MIT license does look good.  Just added it in.
